#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <windows.h>
#include <winioctl.h>
#endif

#define FPL_MONITOR_DEVICE_TYPE 0x8002

#define IOCTL_FPL_MONITOR_GET_EVENTS CTL_CODE(FPL_MONITOR_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_FPL_MONITOR_CLEAR_EVENTS CTL_CODE(FPL_MONITOR_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)

#define FPL_MONITOR_EVENT_CAPACITY 128
#define FPL_MONITOR_PATH_CHARS 160

#define FPL_MONITOR_EVENT_PROCESS 1
#define FPL_MONITOR_EVENT_THREAD 2
#define FPL_MONITOR_EVENT_IMAGE 3

typedef struct _FPL_MONITOR_EVENT {
    ULONG Type;
    ULONG ProcessId;
    ULONG ParentProcessId;
    ULONG ThreadId;
    ULONG ImageBaseLow;
    ULONG ImageSize;
    WCHAR Path[FPL_MONITOR_PATH_CHARS];
} FPL_MONITOR_EVENT;

typedef struct _FPL_MONITOR_EVENT_BATCH {
    ULONG Count;
    FPL_MONITOR_EVENT Events[FPL_MONITOR_EVENT_CAPACITY];
} FPL_MONITOR_EVENT_BATCH;
